inicio
    inteiro x[2][5]
    inteiro i,j
    // Carregando elementos para uma matriz
    para i de 0 ate 1
        para j de 0 até 4
            escrever "Digite o número da linha ", i , " e coluna " , j, ":"
            ler x [i][j]
        proximo
    proximo
    //imprimindo elementos de uma matriz
    para i de 0 ate 1
        para j de 0 ate 4
            escrever "x[", i, "][", j, "]="
            escrever x [i][j], "\n"
        proximo 
    proximo 
fim
